# These are supported funding model platforms

github: [oilmonegov]
# patreon: oilmonegov
# open_collective: laraforge
# ko_fi: oilmonegov
# tidelift: npm/laraforge
# community_bridge: laraforge
# liberapay: oilmonegov
# issuehunt: oilmonegov
# lfx_crowdfunding: laraforge
# polar: oilmonegov
# buy_me_a_coffee: oilmonegov
custom: ['https://oilmonegov.com/sponsor']
