<?php

declare(strict_types=1);

namespace LaraForge\Generators;

use LaraForge\Project\TechnologyStack;
use LaraForge\Support\Generator;

/**
 * Rector Configuration Generator
 *
 * Generates Rector (PHP automated refactoring) configuration
 * based on the project's technology stack and preferences.
 */
final class RectorGenerator extends Generator
{
    public function identifier(): string
    {
        return 'rector';
    }

    public function name(): string
    {
        return 'Rector Configuration';
    }

    public function description(): string
    {
        return 'Generate Rector configuration for automated PHP refactoring';
    }

    /**
     * @return array<string, array{type: string, description: string, required: bool, default?: mixed}>
     */
    public function options(): array
    {
        return [
            'project_path' => [
                'type' => 'string',
                'description' => 'Path to the project',
                'required' => true,
            ],
            'php_version' => [
                'type' => 'string',
                'description' => 'Target PHP version (8.1, 8.2, 8.3, 8.4)',
                'required' => false,
                'default' => '8.4',
            ],
            'laravel_version' => [
                'type' => 'string',
                'description' => 'Laravel version for Laravel-specific rules',
                'required' => false,
                'default' => '11',
            ],
            'sets' => [
                'type' => 'array',
                'description' => 'Rector sets to enable',
                'required' => false,
                'default' => ['dead_code', 'code_quality', 'type_declarations'],
            ],
            'strict_mode' => [
                'type' => 'bool',
                'description' => 'Enable strict mode with more aggressive rules',
                'required' => false,
                'default' => false,
            ],
            'skip_paths' => [
                'type' => 'array',
                'description' => 'Paths to skip during refactoring',
                'required' => false,
                'default' => ['vendor', 'storage', 'bootstrap/cache'],
            ],
        ];
    }

    /**
     * @param  array<string, mixed>  $options
     * @return array<string, string>
     */
    public function generate(array $options): array
    {
        $projectPath = $options['project_path'];
        $phpVersion = $options['php_version'] ?? '8.4';
        $laravelVersion = $options['laravel_version'] ?? '11';
        $sets = $options['sets'] ?? ['dead_code', 'code_quality', 'type_declarations'];
        $strictMode = $options['strict_mode'] ?? false;
        $skipPaths = $options['skip_paths'] ?? ['vendor', 'storage', 'bootstrap/cache'];

        $stack = TechnologyStack::fromPath($projectPath);
        $detected = $stack->detect();

        // Auto-detect versions if not specified
        if (isset($detected['php']['version'])) {
            $phpVersion = $detected['php']['major'].'.'.($detected['php']['minor'] ?? '4');
        }
        if (isset($detected['laravel']['major'])) {
            $laravelVersion = (string) $detected['laravel']['major'];
        }

        $config = $this->buildConfiguration(
            phpVersion: $phpVersion,
            laravelVersion: $laravelVersion,
            sets: $sets,
            strictMode: $strictMode,
            skipPaths: $skipPaths,
            hasLivewire: $stack->has('livewire'),
            hasInertia: $stack->has('inertia'),
        );

        $outputPath = $projectPath.'/rector.php';

        return [
            $outputPath => $config,
        ];
    }

    /**
     * @param  array<string>  $sets
     * @param  array<string>  $skipPaths
     */
    private function buildConfiguration(
        string $phpVersion,
        string $laravelVersion,
        array $sets,
        bool $strictMode,
        array $skipPaths,
        bool $hasLivewire,
        bool $hasInertia,
    ): string {
        $phpSetMethod = $this->getPhpSetMethod($phpVersion);
        $setsCode = $this->buildSetsCode($sets, $strictMode);
        $rulesCode = $this->buildRulesCode($strictMode, $hasLivewire);
        $skipCode = $this->buildSkipCode($skipPaths, $hasLivewire, $hasInertia);
        $laravelCode = $this->buildLaravelCode($laravelVersion);

        return <<<PHP
<?php

declare(strict_types=1);

/**
 * Rector Configuration
 *
 * Automated PHP refactoring configuration generated by LaraForge.
 * Customize this file to match your project's coding standards.
 *
 * Run: composer refactor (to apply changes)
 * Run: composer refactor:dry (to preview changes)
 *
 * @see https://getrector.com/documentation
 */

use Rector\Config\RectorConfig;
{$this->buildUseStatements($sets, $strictMode, $laravelVersion)}

return RectorConfig::configure()
    ->withPaths([
        __DIR__ . '/app',
        __DIR__ . '/config',
        __DIR__ . '/database',
        __DIR__ . '/routes',
        __DIR__ . '/tests',
    ])
{$skipCode}
    ->{$phpSetMethod}
{$setsCode}
{$laravelCode}
{$rulesCode};
PHP;
    }

    private function getPhpSetMethod(string $phpVersion): string
    {
        return match ($phpVersion) {
            '8.1' => 'withPhpSets(php81: true)',
            '8.2' => 'withPhpSets(php82: true)',
            '8.3' => 'withPhpSets(php83: true)',
            default => 'withPhpSets(php84: true)',
        };
    }

    /**
     * @param  array<string>  $sets
     */
    private function buildUseStatements(array $sets, bool $strictMode, string $laravelVersion): string
    {
        $uses = [];

        // Base uses
        $uses[] = 'use Rector\Set\ValueObject\LevelSetList;';
        $uses[] = 'use Rector\Set\ValueObject\SetList;';

        // Type declaration rules
        if (\in_array('type_declarations', $sets, true) || $strictMode) {
            $uses[] = 'use Rector\TypeDeclaration\Rector\ClassMethod\AddVoidReturnTypeWhereNoReturnRector;';
            $uses[] = 'use Rector\TypeDeclaration\Rector\ClassMethod\ReturnTypeFromStrictNativeCallRector;';
            $uses[] = 'use Rector\TypeDeclaration\Rector\Property\TypedPropertyFromAssignsRector;';
        }

        // Code quality rules
        if (\in_array('code_quality', $sets, true)) {
            $uses[] = 'use Rector\CodeQuality\Rector\Class_\InlineConstructorDefaultToPropertyRector;';
            $uses[] = 'use Rector\CodeQuality\Rector\FunctionLike\SimplifyUselessVariableRector;';
        }

        // Dead code rules
        if (\in_array('dead_code', $sets, true)) {
            $uses[] = 'use Rector\DeadCode\Rector\ClassMethod\RemoveUnusedPromotedPropertyRector;';
            $uses[] = 'use Rector\DeadCode\Rector\If_\RemoveAlwaysTrueIfConditionRector;';
        }

        // Strict mode rules
        if ($strictMode) {
            $uses[] = 'use Rector\Strict\Rector\Empty_\DisallowedEmptyRuleFixerRector;';
            $uses[] = 'use Rector\CodingStyle\Rector\Catch_\CatchExceptionNameMatchingTypeRector;';
        }

        // Laravel-specific uses
        if ((int) $laravelVersion >= 10) {
            $uses[] = 'use RectorLaravel\Set\LaravelSetList;';
        }

        return implode("\n", array_unique($uses));
    }

    /**
     * @param  array<string>  $sets
     */
    private function buildSetsCode(array $sets, bool $strictMode): string
    {
        $params = [];

        if (\in_array('dead_code', $sets, true)) {
            $params[] = 'deadCode: true';
        }
        if (\in_array('code_quality', $sets, true)) {
            $params[] = 'codeQuality: true';
        }
        if (\in_array('type_declarations', $sets, true)) {
            $params[] = 'typeDeclarations: true';
        }
        if (\in_array('early_return', $sets, true) || $strictMode) {
            $params[] = 'earlyReturn: true';
        }
        if ($strictMode) {
            $params[] = 'strictBooleans: true';
        }

        if (empty($params)) {
            return '';
        }

        return '    ->withPreparedSets('."\n        ".implode(",\n        ", $params).",\n    )";
    }

    private function buildRulesCode(bool $strictMode, bool $hasLivewire): string
    {
        $rules = [
            'AddVoidReturnTypeWhereNoReturnRector::class',
            'ReturnTypeFromStrictNativeCallRector::class',
            'InlineConstructorDefaultToPropertyRector::class',
            'RemoveUnusedPromotedPropertyRector::class',
        ];

        if ($strictMode) {
            $rules[] = 'TypedPropertyFromAssignsRector::class';
            $rules[] = 'SimplifyUselessVariableRector::class';
            $rules[] = 'RemoveAlwaysTrueIfConditionRector::class';
            $rules[] = 'CatchExceptionNameMatchingTypeRector::class';
        }

        return "    ->withRules([\n        ".implode(",\n        ", $rules).",\n    ])";
    }

    /**
     * @param  array<string>  $skipPaths
     */
    private function buildSkipCode(array $skipPaths, bool $hasLivewire, bool $hasInertia): string
    {
        $paths = [];
        foreach ($skipPaths as $path) {
            $paths[] = "__DIR__ . '/{$path}'";
        }

        // Add framework-specific skips
        if ($hasLivewire) {
            $paths[] = "__DIR__ . '/app/Livewire' // Livewire components may have special conventions";
        }

        $skipRules = [];

        // Skip rules that may cause issues
        $skipRules[] = '// Skip specific files or rules as needed';

        return "    ->withSkip([\n        ".implode(",\n        ", $paths).",\n    ])";
    }

    private function buildLaravelCode(string $laravelVersion): string
    {
        $version = (int) $laravelVersion;

        if ($version < 10) {
            return "    // Laravel {$laravelVersion} - using base PHP rules only";
        }

        return <<<PHP
    // Laravel-specific refactoring rules
    ->withSets([
        LaravelSetList::LARAVEL_{$version}0,
    ])
PHP;
    }

    /**
     * Get Rector rule recommendations based on code analysis.
     *
     * @return array<string, array<string, mixed>>
     */
    public function getRecommendations(string $projectPath): array
    {
        $stack = TechnologyStack::fromPath($projectPath);
        $detected = $stack->detect();
        $phpMajor = $detected['php']['major'] ?? 8;
        $phpMinor = $detected['php']['minor'] ?? 4;

        return [
            'type_declarations' => [
                'description' => 'Add missing type declarations to properties and return types',
                'benefit' => 'Better static analysis, IDE support, and runtime type safety',
                'rules' => [
                    'AddVoidReturnTypeWhereNoReturnRector',
                    'ReturnTypeFromStrictNativeCallRector',
                    'TypedPropertyFromAssignsRector',
                ],
                'recommended' => true,
            ],
            'dead_code' => [
                'description' => 'Remove unused code, variables, and methods',
                'benefit' => 'Cleaner codebase, reduced complexity',
                'rules' => [
                    'RemoveUnusedPromotedPropertyRector',
                    'RemoveAlwaysTrueIfConditionRector',
                    'RemoveUnusedVariableAssignRector',
                ],
                'recommended' => true,
            ],
            'code_quality' => [
                'description' => 'Improve code structure and readability',
                'benefit' => 'More maintainable and consistent code',
                'rules' => [
                    'InlineConstructorDefaultToPropertyRector',
                    'SimplifyUselessVariableRector',
                    'ExplicitBoolCompareRector',
                ],
                'recommended' => true,
            ],
            'early_return' => [
                'description' => 'Convert nested conditions to early returns',
                'benefit' => 'Reduced nesting, better readability',
                'rules' => [
                    'ChangeOrIfContinueToMultiContinueRector',
                    'ChangeNestedForeachIfsToEarlyContinueRector',
                ],
                'recommended' => $phpMajor >= 8,
            ],
            'php_features' => [
                'description' => "Upgrade to PHP {$phpMajor}.{$phpMinor} features",
                'benefit' => 'Modern syntax, better performance',
                'rules' => [
                    'Constructor property promotion',
                    'Named arguments',
                    'Match expressions',
                    'Readonly properties',
                ],
                'recommended' => true,
            ],
            'strict_mode' => [
                'description' => 'Enforce strict type comparisons and boolean handling',
                'benefit' => 'Fewer bugs from type coercion',
                'rules' => [
                    'DisallowedEmptyRuleFixerRector',
                    'StrictArraySearchRector',
                    'StrictInArrayFuncCallAnalyzerRector',
                ],
                'recommended' => false, // Can be breaking
            ],
        ];
    }

    /**
     * Validate if Rector can be safely run on the project.
     *
     * @return array<string, mixed>
     */
    public function validateProject(string $projectPath): array
    {
        $issues = [];
        $warnings = [];

        // Check for git
        if (! is_dir($projectPath.'/.git')) {
            $warnings[] = 'Not a git repository. Recommend committing changes before running Rector.';
        }

        // Check for tests
        if (! is_dir($projectPath.'/tests')) {
            $warnings[] = 'No tests directory found. Consider adding tests before automated refactoring.';
        }

        // Check for composer.json
        if (! file_exists($projectPath.'/composer.json')) {
            $issues[] = 'No composer.json found. Rector requires a Composer project.';
        }

        return [
            'can_run' => empty($issues),
            'issues' => $issues,
            'warnings' => $warnings,
            'recommendations' => [
                'Commit all changes before running Rector',
                'Run tests after Rector to verify changes',
                'Review changes before committing',
                'Use --dry-run first to preview changes',
            ],
        ];
    }
}
