<?php

declare(strict_types=1);

namespace LaraForge\Skills\Contracts;

interface SkillResultInterface
{
    /**
     * Check if the skill execution was successful.
     */
    public function isSuccess(): bool;

    /**
     * Get the primary output of the skill execution.
     */
    public function output(): mixed;

    /**
     * Get any artifacts generated by the skill (files, documents, etc.).
     *
     * @return array<string, mixed>
     */
    public function artifacts(): array;

    /**
     * Get suggested next steps or follow-up skills.
     *
     * @return array<array{skill: string, params?: array, reason?: string}>
     */
    public function nextSteps(): array;

    /**
     * Get the error message if the execution failed.
     */
    public function error(): ?string;

    /**
     * Get additional metadata about the execution.
     *
     * @return array<string, mixed>
     */
    public function metadata(): array;
}
